package com.nobleprog.jbpm;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RequestPojo implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private long processId;
	private java.lang.String processName;
	private java.lang.String name;
	private java.lang.Integer age;
	private java.lang.String profession;
	private java.lang.Integer income;
	private java.lang.String maritalStatus;
	private java.lang.String type;

	public RequestPojo() {
	}

	public long getProcessId() {
		return this.processId;
	}

	public void setProcessId(long processId) {
		this.processId = processId;
	}

	public java.lang.String getProcessName() {
		return this.processName;
	}

	public void setProcessName(java.lang.String processName) {
		this.processName = processName;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public java.lang.String getProfession() {
		return this.profession;
	}

	public void setProfession(java.lang.String profession) {
		this.profession = profession;
	}

	public java.lang.Integer getIncome() {
		return this.income;
	}

	public void setIncome(java.lang.Integer income) {
		this.income = income;
	}

	public java.lang.String getMaritalStatus() {
		return this.maritalStatus;
	}

	public void setMaritalStatus(java.lang.String maritalStatus) {
		this.maritalStatus = maritalStatus;
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public RequestPojo(long processId, java.lang.String processName,
			java.lang.String name, java.lang.Integer age,
			java.lang.String profession, java.lang.Integer income,
			java.lang.String maritalStatus, java.lang.String type) {
		this.processId = processId;
		this.processName = processName;
		this.name = name;
		this.age = age;
		this.profession = profession;
		this.income = income;
		this.maritalStatus = maritalStatus;
		this.type = type;
	}

}